"""MITRE ATT&CK Navigator layer generation from findings."""

from __future__ import annotations


def build_navigator_layer(findings: list[dict]) -> dict:
    """Build ATT&CK Navigator JSON layer from findings."""
    technique_scores: dict[str, int] = {}
    severity_score = {"info": 1, "low": 2, "medium": 3, "high": 4, "critical": 5}

    for f in findings:
        technique_ids = f.get("attack_technique_ids")
        if isinstance(technique_ids, str):
            import json
            try:
                technique_ids = json.loads(technique_ids)
            except (json.JSONDecodeError, TypeError):
                technique_ids = []
        if not technique_ids:
            continue
        for tid in technique_ids:
            score = severity_score.get(f.get("severity", "info"), 1)
            technique_scores[tid] = max(technique_scores.get(tid, 0), score)

    color_map = {1: "#66bb6a", 2: "#ffee58", 3: "#ffa726", 4: "#ef5350", 5: "#b71c1c"}
    techniques = [
        {
            "techniqueID": tid,
            "score": score,
            "color": color_map.get(score, "#ffffff"),
            "comment": f"PACDOOR finding (severity score {score})",
            "enabled": True,
        }
        for tid, score in technique_scores.items()
    ]

    return {
        "name": "PACDOOR Assessment",
        "versions": {"attack": "15", "navigator": "5.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated by PACDOOR",
        "techniques": techniques,
        "gradient": {
            "colors": ["#66bb6a", "#ffee58", "#ffa726", "#ef5350", "#b71c1c"],
            "minValue": 1,
            "maxValue": 5,
        },
    }
